version: "3.7"

services:
  node-red:
    image: nodered/node-red:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    ports:
      - "1880:1880"
    networks:
      node-red-net:
        aliases:
          - nodered
    volumes:
      - node-red_data:/data

volumes:
  node-red_data:

networks:
  node-red-net:
